name: Build Testing Image

on:
  workflow_call:
    inputs:
      timeout:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo testing
